### ISSUE TITLE
NVIDIA OpenCL does not work any more.

### ISSUE THREAD

**Issue by isuruf** [illinois-scicomp/machine-shop-maintenance#69]
Running a simple program like the example from https://documen.tician.de/pyopencl/ fails with
```python
RuntimeError: clBuildProgram failed: BUILD_PROGRAM_FAILURE - clBuildProgram failed: BUILD_PROGRAM_FAILURE - clBuildProgram failed: BUILD_PROGRAM_FAILURE

Build on <pyopencl.Device 'NVIDIA TITAN V' on 'NVIDIA CUDA' at 0x561db0a61db0>:


(options: -I /shared/home/idf2/miniforge3/lib/python3.9/site-packages/pyopencl/cl)
```

**Comment by isuruf** [comment]
This is on bock, but happens on other machines like stout too.

**Comment by kaushikcfd** [comment]
Doing `export LD_LIBRARY_PATH=/usr/bin/lib/x86_64_linux/Nvidia/current` is a fallback that inducer had found and I've been using it for a week.

**Comment by isuruf** [comment]
Thanks for the reply. I tried `export LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu/nvidia/current`, but that didn't work.

**Comment by isuruf** [comment]
This issue is not there on koelsch.

**Comment by kaushikcfd** [comment]
On stout/bock, I am getting this behavior:
```console
(temp_env) kgk2@stout:~/temp/temp_env/src/pyopencl/examples$ echo $LD_LIBRARY_PATH 
/lib/x86_64-linux-gnu/nvidia/current
(temp_env) kgk2@stout:~/temp/temp_env/src/pyopencl/examples$ export PYOPENCL_TEST="nv"
(temp_env) kgk2@stout:~/temp/temp_env/src/pyopencl/examples$ python demo.py 
[0. 0. 0. ... 0. 0. 0.]
0.0
(temp_env) kgk2@stout:~/temp/temp_env/src/pyopencl/examples$ unset LD_LIBRARY_PATH 
(temp_env) kgk2@stout:~/temp/temp_env/src/pyopencl/examples$ python demo.py 
/home/kgk2/temp/temp_env/src/pyopencl/pyopencl/cache.py:516: UserWarning: PyOpenCL compiler caching failed with an exception:
[begin exception]
Traceback (most recent call last):
  File "/home/kgk2/temp/temp_env/src/pyopencl/pyopencl/cache.py", line 493, in create_built_program_from_source_cached
    _create_built_program_from_source_cached(
  File "/home/kgk2/temp/temp_env/src/pyopencl/pyopencl/cache.py", line 438, in _create_built_program_from_source_cached
    result = _cl._Program(ctx, devices, binaries)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pyopencl._cl.RuntimeError: clCreateProgramWithBinary failed: OUT_OF_RESOURCES
[end exception]
  warn("PyOpenCL compiler caching failed with an exception:\n"
Traceback (most recent call last):
  File "/home/kgk2/temp/temp_env/src/pyopencl/examples/demo.py", line 23, in <module>
    """).build()
         ^^^^^^^
  File "/home/kgk2/temp/temp_env/src/pyopencl/pyopencl/__init__.py", line 532, in build
    self._prg, was_cached = self._build_and_catch_errors(
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kgk2/temp/temp_env/src/pyopencl/pyopencl/__init__.py", line 580, in _build_and_catch_errors
    raise err
pyopencl._cl.RuntimeError: clBuildProgram failed: BUILD_PROGRAM_FAILURE - clBuildProgram failed: BUILD_PROGRAM_FAILURE - clBuildProgram failed: BUILD_PROGRAM_FAILURE

Build on <pyopencl.Device 'NVIDIA TITAN V' on 'NVIDIA CUDA' at 0x24b8230>:


(options: -I /home/kgk2/temp/temp_env/src/pyopencl/pyopencl/cl)
(source saved as /tmp/tmpgj078fa3.cl)
```

**Comment by isuruf** [comment]
I just installled `libnvidia-nvvm4` on bock and it works now with LD_LIBRARY_PATH.

**Comment by isuruf** [comment]
It seems `libnvidia-nvvm4` is already installed on stout, so LD_LIBRARY_PATH hack works now.

**Comment by isuruf** [comment]
There are update-alternatives links created for all the nvidia libraries except for `libnvidia-nvvm.so.4`. @inducer, is there a script you use to make these links or are they made by a dpkg package?

**Comment by inducer** [comment]
2aaec75 might work around this for now. The alternatives links are created by packages, so I suspect a packaging bug.
